apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontdoor-v1
  namespace: adpcore
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontdoor
  template:
    metadata:
      labels:
        app: frontdoor
        version: v1
    spec:
      containers:
      - name: frontdoor
        image: acradpdemo.azurecr.io/monitoring-frontdoor-api:v1
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: frontdoor-secrets
                key: ASPNETCORE_ENVIRONMENT
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            valueFrom:
              secretKeyRef:
                name: frontdoor-secrets
                key: APPINSIGHTS_INSTRUMENTATIONKEY
          - name: FRONTDOOR_AAD_APP_ID
            valueFrom:
              secretKeyRef:
                name: frontdoor-secrets
                key: FRONTDOOR_AAD_APP_ID
          - name: FRONTDOOR_AAD_APP_URI
            valueFrom:
              secretKeyRef:
                name: frontdoor-secrets
                key: FRONTDOOR_AAD_APP_URI
          - name: FRONTDOOR_AAD_APP_SECRET
            valueFrom:
              secretKeyRef:
                name: frontdoor-secrets
                key: FRONTDOOR_AAD_APP_SECRET
          - name: FRONTDOOR_AAD_AUTHORITY
            valueFrom:
              secretKeyRef:
                name: frontdoor-secrets
                key: FRONTDOOR_AAD_AUTHORITY
          - name: FRONTDOOR_ADX_CLUSTER
            valueFrom:
              secretKeyRef:
                name: frontdoor-secrets
                key: FRONTDOOR_ADX_CLUSTER
          - name: FRONTDOOR_ADX_DATABASE
            valueFrom:
              secretKeyRef:
                name: frontdoor-secrets
                key: FRONTDOOR_ADX_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: frontdoor
  namespace: adpcore
  labels: 
    app: frontdoor
spec:
  selector:
    app: frontdoor
  ports:
  - name: http
    port: 80